# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jaydeep Chauhan
title: Machine Learning Engineer
email: jtchauha@iu.edu
phone: +1(630)943-9664

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  Jd8111997
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: jaydeep-chauhan-57ab3171
# xing_username: jekyll
# pinterest_username: jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Kaggle
  icon: fab fa-kaggle
  url: https://www.kaggle.com/jd81197
- title: Resume
  icon: far fa-file-pdf
  url: https://github.com/Jd8111997/Jd8111997/blob/main/assets/Resume.pdf


# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Jaydeep! I'm obsessed with lot of things, especially understanding the complex ML algorithms in the most intuitive manner, interpretability of Deep Learning systems, solving some real world problems using AI that can make the world a better place to live. My long term goal is to create ML models which are robust, could able to learn from very few samples, generalize beyond iid settings and can do a high level reasoning about the world. I consider myself polymath and I love connecting dots between AI and different fields.                     
  
  I'm currently pursuing Masters in Computer science from Indiana University Bloomington. Prior to joining IUB, I was working as a Assocaite Data Scientist for a Indian start up called : 'ParallelDots'.                                     

  If you are also excited about any of the topics that I mentioned above and want to share your thought, feel free to reach out to me. You can mail me or reach out to me via LinkedIn.                               
  Thanks for being here.


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Volumetric rendering using Neural Radiance Fields
        link: github.com/Jd8111997/NeRF
        # link_text: Project Website
        additional_links:
          - title:  Github
            icon: fab fa-github
            url: github.com/Jd8111997/NeRF
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is one of the coolest application of computer vision!
        description: | # this will include new lines to allow paragraphs
          This project is based on an implementation of NeRF(https://www.matthewtancik.com/nerf) paper to render a novel 3D view of a scene. The objective of this project was to learn about the 3D view reconstruction, neural rendering and depth estimation using latest state of the art model in computer vision.

      - layout: top-middle
        title: Supervised Contrastive Learning for pretrained language models
        link: github.com/Jd8111997/Supervised-contrastive-learning
        # link_text: Project Website
        additional_links:
          - title:  Github
            icon: fab fa-github
            url: github.com/Jd8111997/Supervised-contrastive-learning
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Supervised contrastive learning proves a great technique for few shot learning!
        description: | # this will include new lines to allow paragraphs
          This project is based on an implementation of supervised contrastive learning for pretrained language models paper(https://arxiv.org/abs/2011.01403).The main objective behind this project was to learn about few shot learning for data hungry large language models. We got fascinating results to see that after applying supervised contrastive loss; the model is able to learn a very good representation of discriminative features from very few samples. 

      - layout: top-middle
        title: Speech Enhancer
        link: github.com/Jd8111997/Speech-Enhancer
        # link_text: Project Website
        additional_links:
          - title:  Github
            icon: fab fa-github
            url: github.com/Jd8111997/Speech-Enhancer
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          I built it to enhance my crappy guitar riffs!
        description: | # this will include new lines to allow paragraphs
          This purpose of working on this project was to explore the domain of speech enhancement by incorporating Speech Enhancement Generative Adversarial Networks.

      - layout: top-middle
        title: Autoregressive Generative Models
        link: github.com/Jd8111997/Auto-regressive-models
        # link_text: Project Website
        additional_links:
          - title:  Github
            icon: fab fa-github
            url: github.com/Jd8111997/Auto-regressive-models
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Feeling bored, let's make an AI model to generate some dog images:)
        description: | # this will include new lines to allow paragraphs
          This project is based on an implementation of Autoregressive Generative Models such as PixelCNN, PixelCNN++ and GatedPixelCNN to generate a novel images of a dog.

      - layout: top-middle
        title: Matrix optimization using Angular and Python
        link: github.com/Jd8111997/ChatClub
        # link_text: Project Website
        additional_links:
          - title:  Github
            icon: fab fa-github
            url: github.com/Jd8111997/ChatClub
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          After watching Silicon Valley TV series, I got inspired to work on decentralized chatting application.
        description: | # this will include new lines to allow paragraphs
          The main objective for working on this project was to learn more about decentralization concepts and algorithms by developing a decentralized chat application based on popular open-source matrix protocol and synapse server using Angular as front-end and Python-twisted as a backend.

      - layout: top-middle
        title: Duplicate Image Detection Tool
        link: github.com/Jd8111997/Duplicate-Image-Detection-Tool
        # link_text: Project Website
        additional_links:
          - title:  Github
            icon: fab fa-github
            url: github.com/Jd8111997/Duplicate-Image-Detection-Tool
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Isn't it too tiring to manually delete duplicate images from computer ?
        description: | # this will include new lines to allow paragraphs
          This project was a PyQt based GUI application that can detect Duplicate Images by sensitivity hasing algorithm; It can also detect the noisy images and can automatically delete them based on the threshold.

      - layout: top-middle
        title: Music Recommendation Engine
        link: github.com/Jd8111997/Music-Recommedation-Engine
        # link_text: Project Website
        additional_links:
          - title:  Github
            icon: fab fa-github
            url: github.com/Jd8111997/Music-Recommedation-Engine
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Collaborative filtering won't work if you don't have enough data.
        description: | # this will include new lines to allow paragraphs
          Beats is a music hosting site and music recommendation engine built in C# using collaborative filtering algorithms.

       


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Vimaan Robotics
        link: https://vimaan.ai/
        # link_text: https://vimaan.ai/
        sub_title: Computer Vision Research Intern
        caption: June 2022 - Sept 2022
        quote: >
          Do you know, Failure to ensure accurate tracking of inventory can cost millions of dollars every year even within a single warehouse!!!
        description: | # this will include new lines to allow paragraphs
            - Image Quality Assessment(IQA): Developed a new ’No reference Image Quality Assessment’ method using deep learning that can help to assess an image quality and helps to locate the distorted regions in an image in a multi task setting.                                          
            - Data valuation: Worked on data valuation methods to quantify the sample quality using meta reinforcement learning approach.                                                              
            - Image enhancement: Worked on developing a pipeline for Image enhancement using a state of the art image debluring methods.    

      - layout: left
        title: ParallelDots Inc.
        link: https://www.paralleldots.com/
        # link_text: https://www.paralleldots.com/
        sub_title: Associate Data Scientist - DL Research
        caption: Nov 2020 - Jul 2021
        quote: >
          Solving some amazing problems in shelf retail execution using AI.
        description: | # this will include new lines to allow paragraphs
            - Object Detection Benchmarking: Contributed in benchmarking of Domain Invariant Object Detectors across various client datasets and tried various state of the art object detection models to replace generalized object detector in ShelfWatch(main product of the company).                                                                                              
            - Training Object Detectors & Classifiers: Training object detection models and product classifier on various client datasets to achieve high accuracy and good generalization on out of distribution classes.                                                                                                                                                        
            - Object Detection for Mobile Device: Training a object detection models for mobile devices.                                        
            - Research Work: Contributed in a ongoing research work in semi supervised learning for dense object detection and our work got published in CVPR 2021 retailvision workshop.

      - layout: left
        title: Bhaskaracharya Institute For Space Applications and Geo-Informatics.
        link: https://bisag-n.gov.in/
        # link_text: https://bisag-n.gov.in/
        sub_title: Software Engineering Intern
        caption: Dec 2018 - Mar 2019
        quote: >
          Credits goes to a Pied-piper's idea of new internet!!
        description: | # this will include new lines to allow paragraphs
            - I Developed a decentralized chatting application for BISAG scientists based on open source framework : ’Matrix Synapse ’, with functionalities such as user registration, emoji and multimedia file sending, birthday wish, delete a message, create and change group-name etc; using Python, Angular and SQLite.                                

                                                      

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Indiana University
        caption: Aug 2021 - May 2023
        sub_title: Masters in Computer Science
        quote: >
          IU is considered one of the most beautiful campus in the US.
        description: | # this will include new lines to allow paragraphs
          - During my masters, I have studied many interesting subjects : Applied Algorithms, Elements of AI, Machine Learning, Computer Vision, Advance OS, Applied ML for Computational Linguistics, Music Data mining.                                                              
          - Currently, I'm doing Masters Thesis on generalization under distributional shifts, disentanglement and causality in deep learning under the guidance of Prof. David Crandall.                   

  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Languages  :  Python, R, C/C++, JavaScript, Java SE, SQL, Bash, PHP     
      - Libraries  :  PyTorch, Scikit, NLTK, Matplotlib, TensorFlow, Keras, JAX, Pandas, Scipy, Plotly                           
      - Tools  :  GIT, MySQL, SQLite, Docker, Wandb, Kubernetes, Latex 

  - title: Honors and Awards
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Won a silver medal for Cassava Leaf Disease Classification challenge on kaggle(top 4% worldwide). - Jan 21   
      - Won a silver medal for SIIM-ISIC Melanoma Classification challenge on kaggle (ranked top 2% worldwide) - Aug 20                          
      - Expert’ in Kaggle Competitions(Current rank 1174 out of 166,012)

  - title: Publication
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Semi-supervised Learning for Dense Object Detection in Retail Scenes: [CVPR 2021 RetailVision Workshop](https://retailvisionworkshop.github.io/cvpr2021/)        
      - Comparative study of GAN and VAE: [International Journal of Computer Applications (0975 - 8887) Volume 182 - No.22, October 2018](https://www.ijcaonline.org/archives/volume182/number22/chauhan-2018-ijca-918039.pdf) 

                          
  
  
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside tinkering with ML models, some of my other interests and hobbies are:
      - Playing riffs on guitar(Currently I'm learning to play Nothing else matters by Metallica)
      - Excercising
      - Cooking
      - Watching stand up comedies                                        
      - Reading fictions(Currently I'm finishing Brothers Karmazov)                                 
      - Musing and trying to connect dots between science, arts, philosophy and history 

  - title: My Bucket list
    layout: text
    content: | # this will include new lines to allow paragraphs
     - Build my own RV and travel across all the states in the US                 
     - Visit a F1 circuit at Monte Carlo
     - Learn surfing and sky diving
     - Produce my own music                    

# Footer
footer_show_references: False
references_title: Jaydeep Chauhan

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
